package mapeo;
// Generated 26-03-2012 12:57:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cabecera101 generated by hbm2java
 */
public class Cabecera101  implements java.io.Serializable {


     private long id101;
     private OrdenDeCompra ordenDeCompra;
     private Date fecha101;
     private Integer nprovi101;
     private String estado101;
     private Double totalgral101;
     private Set items = new HashSet(0);
     private Set rdp101s = new HashSet(0);
     private Set ext101s = new HashSet(0);
     private Set zfe101s = new HashSet(0);
     private Set documentoAdjuntos = new HashSet(0);

    public Cabecera101() {
    }

	
    public Cabecera101(long id101, OrdenDeCompra ordenDeCompra) {
        this.id101 = id101;
        this.ordenDeCompra = ordenDeCompra;
    }
    public Cabecera101(long id101, OrdenDeCompra ordenDeCompra, Date fecha101, Integer nprovi101, String estado101, Double totalgral101, Set items, Set rdp101s, Set ext101s, Set zfe101s, Set documentoAdjuntos) {
       this.id101 = id101;
       this.ordenDeCompra = ordenDeCompra;
       this.fecha101 = fecha101;
       this.nprovi101 = nprovi101;
       this.estado101 = estado101;
       this.totalgral101 = totalgral101;
       this.items = items;
       this.rdp101s = rdp101s;
       this.ext101s = ext101s;
       this.zfe101s = zfe101s;
       this.documentoAdjuntos = documentoAdjuntos;
    }
   
    public long getId101() {
        return this.id101;
    }
    
    public void setId101(long id101) {
        this.id101 = id101;
    }
    public OrdenDeCompra getOrdenDeCompra() {
        return this.ordenDeCompra;
    }
    
    public void setOrdenDeCompra(OrdenDeCompra ordenDeCompra) {
        this.ordenDeCompra = ordenDeCompra;
    }
    public Date getFecha101() {
        return this.fecha101;
    }
    
    public void setFecha101(Date fecha101) {
        this.fecha101 = fecha101;
    }
    public Integer getNprovi101() {
        return this.nprovi101;
    }
    
    public void setNprovi101(Integer nprovi101) {
        this.nprovi101 = nprovi101;
    }
    public String getEstado101() {
        return this.estado101;
    }
    
    public void setEstado101(String estado101) {
        this.estado101 = estado101;
    }
    public Double getTotalgral101() {
        return this.totalgral101;
    }
    
    public void setTotalgral101(Double totalgral101) {
        this.totalgral101 = totalgral101;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }
    public Set getRdp101s() {
        return this.rdp101s;
    }
    
    public void setRdp101s(Set rdp101s) {
        this.rdp101s = rdp101s;
    }
    public Set getExt101s() {
        return this.ext101s;
    }
    
    public void setExt101s(Set ext101s) {
        this.ext101s = ext101s;
    }
    public Set getZfe101s() {
        return this.zfe101s;
    }
    
    public void setZfe101s(Set zfe101s) {
        this.zfe101s = zfe101s;
    }
    public Set getDocumentoAdjuntos() {
        return this.documentoAdjuntos;
    }
    
    public void setDocumentoAdjuntos(Set documentoAdjuntos) {
        this.documentoAdjuntos = documentoAdjuntos;
    }




}


