package mapeo;
// Generated 26-03-2012 12:57:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cabecera201 generated by hbm2java
 */
public class Cabecera201  implements java.io.Serializable {


     private long id201;
     private NotaDeVenta notaDeVenta;
     private Integer nprovi201;
     private Date fecha201;
     private String estado201;
     private Double totalgraal201;
     private Set extZfe201s = new HashSet(0);
     private Set extRdp201s = new HashSet(0);
     private Set items = new HashSet(0);
     private Set extOzf201s = new HashSet(0);

    public Cabecera201() {
    }

	
    public Cabecera201(long id201, NotaDeVenta notaDeVenta) {
        this.id201 = id201;
        this.notaDeVenta = notaDeVenta;
    }
    public Cabecera201(long id201, NotaDeVenta notaDeVenta, Integer nprovi201, Date fecha201, String estado201, Double totalgraal201, Set extZfe201s, Set extRdp201s, Set items, Set extOzf201s) {
       this.id201 = id201;
       this.notaDeVenta = notaDeVenta;
       this.nprovi201 = nprovi201;
       this.fecha201 = fecha201;
       this.estado201 = estado201;
       this.totalgraal201 = totalgraal201;
       this.extZfe201s = extZfe201s;
       this.extRdp201s = extRdp201s;
       this.items = items;
       this.extOzf201s = extOzf201s;
    }
   
    public long getId201() {
        return this.id201;
    }
    
    public void setId201(long id201) {
        this.id201 = id201;
    }
    public NotaDeVenta getNotaDeVenta() {
        return this.notaDeVenta;
    }
    
    public void setNotaDeVenta(NotaDeVenta notaDeVenta) {
        this.notaDeVenta = notaDeVenta;
    }
    public Integer getNprovi201() {
        return this.nprovi201;
    }
    
    public void setNprovi201(Integer nprovi201) {
        this.nprovi201 = nprovi201;
    }
    public Date getFecha201() {
        return this.fecha201;
    }
    
    public void setFecha201(Date fecha201) {
        this.fecha201 = fecha201;
    }
    public String getEstado201() {
        return this.estado201;
    }
    
    public void setEstado201(String estado201) {
        this.estado201 = estado201;
    }
    public Double getTotalgraal201() {
        return this.totalgraal201;
    }
    
    public void setTotalgraal201(Double totalgraal201) {
        this.totalgraal201 = totalgraal201;
    }
    public Set getExtZfe201s() {
        return this.extZfe201s;
    }
    
    public void setExtZfe201s(Set extZfe201s) {
        this.extZfe201s = extZfe201s;
    }
    public Set getExtRdp201s() {
        return this.extRdp201s;
    }
    
    public void setExtRdp201s(Set extRdp201s) {
        this.extRdp201s = extRdp201s;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }
    public Set getExtOzf201s() {
        return this.extOzf201s;
    }
    
    public void setExtOzf201s(Set extOzf201s) {
        this.extOzf201s = extOzf201s;
    }




}


