package mapeo;
// Generated 26-03-2012 12:57:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String perRut;
     private Persona persona;
     private Date fechaRegistro;
     private String usuarioZonafr;

    public Cliente() {
    }

	
    public Cliente(String perRut, Persona persona) {
        this.perRut = perRut;
        this.persona = persona;
    }
    public Cliente(String perRut, Persona persona, Date fechaRegistro, String usuarioZonafr) {
       this.perRut = perRut;
       this.persona = persona;
       this.fechaRegistro = fechaRegistro;
       this.usuarioZonafr = usuarioZonafr;
    }
   
    public String getPerRut() {
        return this.perRut;
    }
    
    public void setPerRut(String perRut) {
        this.perRut = perRut;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getUsuarioZonafr() {
        return this.usuarioZonafr;
    }
    
    public void setUsuarioZonafr(String usuarioZonafr) {
        this.usuarioZonafr = usuarioZonafr;
    }




}


