package mapeo;
// Generated 26-03-2012 12:57:47 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private String empRut;
     private String empNfantasia;
     private String empRsocial;
     private String empGcomercial;
     private String empDireccion;
     private String empCiudad;
     private String empFono;
     private String empReplegal;
     private String empNomreplegal;
     private String empEstado;
     private Set trabajadors = new HashSet(0);
     private Set galpons = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(String empRut) {
        this.empRut = empRut;
    }
    public Empresa(String empRut, String empNfantasia, String empRsocial, String empGcomercial, String empDireccion, String empCiudad, String empFono, String empReplegal, String empNomreplegal, String empEstado, Set trabajadors, Set galpons) {
       this.empRut = empRut;
       this.empNfantasia = empNfantasia;
       this.empRsocial = empRsocial;
       this.empGcomercial = empGcomercial;
       this.empDireccion = empDireccion;
       this.empCiudad = empCiudad;
       this.empFono = empFono;
       this.empReplegal = empReplegal;
       this.empNomreplegal = empNomreplegal;
       this.empEstado = empEstado;
       this.trabajadors = trabajadors;
       this.galpons = galpons;
    }
   
    public String getEmpRut() {
        return this.empRut;
    }
    
    public void setEmpRut(String empRut) {
        this.empRut = empRut;
    }
    public String getEmpNfantasia() {
        return this.empNfantasia;
    }
    
    public void setEmpNfantasia(String empNfantasia) {
        this.empNfantasia = empNfantasia;
    }
    public String getEmpRsocial() {
        return this.empRsocial;
    }
    
    public void setEmpRsocial(String empRsocial) {
        this.empRsocial = empRsocial;
    }
    public String getEmpGcomercial() {
        return this.empGcomercial;
    }
    
    public void setEmpGcomercial(String empGcomercial) {
        this.empGcomercial = empGcomercial;
    }
    public String getEmpDireccion() {
        return this.empDireccion;
    }
    
    public void setEmpDireccion(String empDireccion) {
        this.empDireccion = empDireccion;
    }
    public String getEmpCiudad() {
        return this.empCiudad;
    }
    
    public void setEmpCiudad(String empCiudad) {
        this.empCiudad = empCiudad;
    }
    public String getEmpFono() {
        return this.empFono;
    }
    
    public void setEmpFono(String empFono) {
        this.empFono = empFono;
    }
    public String getEmpReplegal() {
        return this.empReplegal;
    }
    
    public void setEmpReplegal(String empReplegal) {
        this.empReplegal = empReplegal;
    }
    public String getEmpNomreplegal() {
        return this.empNomreplegal;
    }
    
    public void setEmpNomreplegal(String empNomreplegal) {
        this.empNomreplegal = empNomreplegal;
    }
    public String getEmpEstado() {
        return this.empEstado;
    }
    
    public void setEmpEstado(String empEstado) {
        this.empEstado = empEstado;
    }
    public Set getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set trabajadors) {
        this.trabajadors = trabajadors;
    }
    public Set getGalpons() {
        return this.galpons;
    }
    
    public void setGalpons(Set galpons) {
        this.galpons = galpons;
    }




}


