package mapeo;
// Generated 26-03-2012 12:57:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Ext101 generated by hbm2java
 */
public class Ext101  implements java.io.Serializable {


     private long id101;
     private Cabecera101 cabecera101;
     private Long ocId;
     private Date fecha101;
     private Integer nprovi101;
     private String extPembarque;
     private String extPaisproced;
     private String extClausula;
     private Double extFob;
     private Double extFlete;
     private Double extSeguro;
     private Double extCif;
     private String extTransext;
     private String extTransnacional;
     private String extMediotranscod2;

    public Ext101() {
    }

	
    public Ext101(long id101, Cabecera101 cabecera101) {
        this.id101 = id101;
        this.cabecera101 = cabecera101;
    }
    public Ext101(long id101, Cabecera101 cabecera101, Long ocId, Date fecha101, Integer nprovi101, String extPembarque, String extPaisproced, String extClausula, Double extFob, Double extFlete, Double extSeguro, Double extCif, String extTransext, String extTransnacional, String extMediotranscod2) {
       this.id101 = id101;
       this.cabecera101 = cabecera101;
       this.ocId = ocId;
       this.fecha101 = fecha101;
       this.nprovi101 = nprovi101;
       this.extPembarque = extPembarque;
       this.extPaisproced = extPaisproced;
       this.extClausula = extClausula;
       this.extFob = extFob;
       this.extFlete = extFlete;
       this.extSeguro = extSeguro;
       this.extCif = extCif;
       this.extTransext = extTransext;
       this.extTransnacional = extTransnacional;
       this.extMediotranscod2 = extMediotranscod2;
    }
   
    public long getId101() {
        return this.id101;
    }
    
    public void setId101(long id101) {
        this.id101 = id101;
    }
    public Cabecera101 getCabecera101() {
        return this.cabecera101;
    }
    
    public void setCabecera101(Cabecera101 cabecera101) {
        this.cabecera101 = cabecera101;
    }
    public Long getOcId() {
        return this.ocId;
    }
    
    public void setOcId(Long ocId) {
        this.ocId = ocId;
    }
    public Date getFecha101() {
        return this.fecha101;
    }
    
    public void setFecha101(Date fecha101) {
        this.fecha101 = fecha101;
    }
    public Integer getNprovi101() {
        return this.nprovi101;
    }
    
    public void setNprovi101(Integer nprovi101) {
        this.nprovi101 = nprovi101;
    }
    public String getExtPembarque() {
        return this.extPembarque;
    }
    
    public void setExtPembarque(String extPembarque) {
        this.extPembarque = extPembarque;
    }
    public String getExtPaisproced() {
        return this.extPaisproced;
    }
    
    public void setExtPaisproced(String extPaisproced) {
        this.extPaisproced = extPaisproced;
    }
    public String getExtClausula() {
        return this.extClausula;
    }
    
    public void setExtClausula(String extClausula) {
        this.extClausula = extClausula;
    }
    public Double getExtFob() {
        return this.extFob;
    }
    
    public void setExtFob(Double extFob) {
        this.extFob = extFob;
    }
    public Double getExtFlete() {
        return this.extFlete;
    }
    
    public void setExtFlete(Double extFlete) {
        this.extFlete = extFlete;
    }
    public Double getExtSeguro() {
        return this.extSeguro;
    }
    
    public void setExtSeguro(Double extSeguro) {
        this.extSeguro = extSeguro;
    }
    public Double getExtCif() {
        return this.extCif;
    }
    
    public void setExtCif(Double extCif) {
        this.extCif = extCif;
    }
    public String getExtTransext() {
        return this.extTransext;
    }
    
    public void setExtTransext(String extTransext) {
        this.extTransext = extTransext;
    }
    public String getExtTransnacional() {
        return this.extTransnacional;
    }
    
    public void setExtTransnacional(String extTransnacional) {
        this.extTransnacional = extTransnacional;
    }
    public String getExtMediotranscod2() {
        return this.extMediotranscod2;
    }
    
    public void setExtMediotranscod2(String extMediotranscod2) {
        this.extMediotranscod2 = extMediotranscod2;
    }




}


