package mapeo;
// Generated 26-03-2012 12:57:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ExtOzf201 generated by hbm2java
 */
public class ExtOzf201  implements java.io.Serializable {


     private long id201;
     private Cabecera201 cabecera201;
     private Long nvId;
     private Integer nprovi201;
     private Date fecha201;
     private String extozfAduanadest;
     private String extozfAvanzada;
     private String extozfViatransporte;
     private String extozfPlazo;

    public ExtOzf201() {
    }

	
    public ExtOzf201(long id201, Cabecera201 cabecera201) {
        this.id201 = id201;
        this.cabecera201 = cabecera201;
    }
    public ExtOzf201(long id201, Cabecera201 cabecera201, Long nvId, Integer nprovi201, Date fecha201, String extozfAduanadest, String extozfAvanzada, String extozfViatransporte, String extozfPlazo) {
       this.id201 = id201;
       this.cabecera201 = cabecera201;
       this.nvId = nvId;
       this.nprovi201 = nprovi201;
       this.fecha201 = fecha201;
       this.extozfAduanadest = extozfAduanadest;
       this.extozfAvanzada = extozfAvanzada;
       this.extozfViatransporte = extozfViatransporte;
       this.extozfPlazo = extozfPlazo;
    }
   
    public long getId201() {
        return this.id201;
    }
    
    public void setId201(long id201) {
        this.id201 = id201;
    }
    public Cabecera201 getCabecera201() {
        return this.cabecera201;
    }
    
    public void setCabecera201(Cabecera201 cabecera201) {
        this.cabecera201 = cabecera201;
    }
    public Long getNvId() {
        return this.nvId;
    }
    
    public void setNvId(Long nvId) {
        this.nvId = nvId;
    }
    public Integer getNprovi201() {
        return this.nprovi201;
    }
    
    public void setNprovi201(Integer nprovi201) {
        this.nprovi201 = nprovi201;
    }
    public Date getFecha201() {
        return this.fecha201;
    }
    
    public void setFecha201(Date fecha201) {
        this.fecha201 = fecha201;
    }
    public String getExtozfAduanadest() {
        return this.extozfAduanadest;
    }
    
    public void setExtozfAduanadest(String extozfAduanadest) {
        this.extozfAduanadest = extozfAduanadest;
    }
    public String getExtozfAvanzada() {
        return this.extozfAvanzada;
    }
    
    public void setExtozfAvanzada(String extozfAvanzada) {
        this.extozfAvanzada = extozfAvanzada;
    }
    public String getExtozfViatransporte() {
        return this.extozfViatransporte;
    }
    
    public void setExtozfViatransporte(String extozfViatransporte) {
        this.extozfViatransporte = extozfViatransporte;
    }
    public String getExtozfPlazo() {
        return this.extozfPlazo;
    }
    
    public void setExtozfPlazo(String extozfPlazo) {
        this.extozfPlazo = extozfPlazo;
    }




}


