package mapeo;
// Generated 26-03-2012 12:57:47 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Familia generated by hbm2java
 */
public class Familia  implements java.io.Serializable {


     private long famId;
     private String famNombre;
     private String famDescripcion;
     private String famEstado;
     private Set productos = new HashSet(0);

    public Familia() {
    }

	
    public Familia(long famId) {
        this.famId = famId;
    }
    public Familia(long famId, String famNombre, String famDescripcion, String famEstado, Set productos) {
       this.famId = famId;
       this.famNombre = famNombre;
       this.famDescripcion = famDescripcion;
       this.famEstado = famEstado;
       this.productos = productos;
    }
   
    public long getFamId() {
        return this.famId;
    }
    
    public void setFamId(long famId) {
        this.famId = famId;
    }
    public String getFamNombre() {
        return this.famNombre;
    }
    
    public void setFamNombre(String famNombre) {
        this.famNombre = famNombre;
    }
    public String getFamDescripcion() {
        return this.famDescripcion;
    }
    
    public void setFamDescripcion(String famDescripcion) {
        this.famDescripcion = famDescripcion;
    }
    public String getFamEstado() {
        return this.famEstado;
    }
    
    public void setFamEstado(String famEstado) {
        this.famEstado = famEstado;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


