package mapeo;
// Generated 26-03-2012 12:57:47 AM by Hibernate Tools 3.2.1.GA



/**
 * Galpon generated by hbm2java
 */
public class Galpon  implements java.io.Serializable {


     private int idGalpon;
     private Empresa empresa;
     private String recintoGalpon;
     private String manzanaGalpon;
     private String descripcionGalpon;
     private Integer fonoGalpon;
     private String estadoGalpon;

    public Galpon() {
    }

	
    public Galpon(int idGalpon, Empresa empresa) {
        this.idGalpon = idGalpon;
        this.empresa = empresa;
    }
    public Galpon(int idGalpon, Empresa empresa, String recintoGalpon, String manzanaGalpon, String descripcionGalpon, Integer fonoGalpon, String estadoGalpon) {
       this.idGalpon = idGalpon;
       this.empresa = empresa;
       this.recintoGalpon = recintoGalpon;
       this.manzanaGalpon = manzanaGalpon;
       this.descripcionGalpon = descripcionGalpon;
       this.fonoGalpon = fonoGalpon;
       this.estadoGalpon = estadoGalpon;
    }
   
    public int getIdGalpon() {
        return this.idGalpon;
    }
    
    public void setIdGalpon(int idGalpon) {
        this.idGalpon = idGalpon;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getRecintoGalpon() {
        return this.recintoGalpon;
    }
    
    public void setRecintoGalpon(String recintoGalpon) {
        this.recintoGalpon = recintoGalpon;
    }
    public String getManzanaGalpon() {
        return this.manzanaGalpon;
    }
    
    public void setManzanaGalpon(String manzanaGalpon) {
        this.manzanaGalpon = manzanaGalpon;
    }
    public String getDescripcionGalpon() {
        return this.descripcionGalpon;
    }
    
    public void setDescripcionGalpon(String descripcionGalpon) {
        this.descripcionGalpon = descripcionGalpon;
    }
    public Integer getFonoGalpon() {
        return this.fonoGalpon;
    }
    
    public void setFonoGalpon(Integer fonoGalpon) {
        this.fonoGalpon = fonoGalpon;
    }
    public String getEstadoGalpon() {
        return this.estadoGalpon;
    }
    
    public void setEstadoGalpon(String estadoGalpon) {
        this.estadoGalpon = estadoGalpon;
    }




}


