package mapeo;
// Generated 26-03-2012 12:57:47 AM by Hibernate Tools 3.2.1.GA



/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private int itmNumero;
     private OrdenDeCompra ordenDeCompra;
     private Cabecera201 cabecera201;
     private NotaDeVenta notaDeVenta;
     private Cabecera101 cabecera101;
     private Producto producto;
     private Double itmCantidad;
     private Double itmCifunivta;
     private Double itmCiftotal;

    public Item() {
    }

	
    public Item(int itmNumero, Producto producto) {
        this.itmNumero = itmNumero;
        this.producto = producto;
    }
    public Item(int itmNumero, OrdenDeCompra ordenDeCompra, Cabecera201 cabecera201, NotaDeVenta notaDeVenta, Cabecera101 cabecera101, Producto producto, Double itmCantidad, Double itmCifunivta, Double itmCiftotal) {
       this.itmNumero = itmNumero;
       this.ordenDeCompra = ordenDeCompra;
       this.cabecera201 = cabecera201;
       this.notaDeVenta = notaDeVenta;
       this.cabecera101 = cabecera101;
       this.producto = producto;
       this.itmCantidad = itmCantidad;
       this.itmCifunivta = itmCifunivta;
       this.itmCiftotal = itmCiftotal;
    }
   
    public int getItmNumero() {
        return this.itmNumero;
    }
    
    public void setItmNumero(int itmNumero) {
        this.itmNumero = itmNumero;
    }
    public OrdenDeCompra getOrdenDeCompra() {
        return this.ordenDeCompra;
    }
    
    public void setOrdenDeCompra(OrdenDeCompra ordenDeCompra) {
        this.ordenDeCompra = ordenDeCompra;
    }
    public Cabecera201 getCabecera201() {
        return this.cabecera201;
    }
    
    public void setCabecera201(Cabecera201 cabecera201) {
        this.cabecera201 = cabecera201;
    }
    public NotaDeVenta getNotaDeVenta() {
        return this.notaDeVenta;
    }
    
    public void setNotaDeVenta(NotaDeVenta notaDeVenta) {
        this.notaDeVenta = notaDeVenta;
    }
    public Cabecera101 getCabecera101() {
        return this.cabecera101;
    }
    
    public void setCabecera101(Cabecera101 cabecera101) {
        this.cabecera101 = cabecera101;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Double getItmCantidad() {
        return this.itmCantidad;
    }
    
    public void setItmCantidad(Double itmCantidad) {
        this.itmCantidad = itmCantidad;
    }
    public Double getItmCifunivta() {
        return this.itmCifunivta;
    }
    
    public void setItmCifunivta(Double itmCifunivta) {
        this.itmCifunivta = itmCifunivta;
    }
    public Double getItmCiftotal() {
        return this.itmCiftotal;
    }
    
    public void setItmCiftotal(Double itmCiftotal) {
        this.itmCiftotal = itmCiftotal;
    }




}


