package mapeo;
// Generated 26-03-2012 12:57:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenDeCompra generated by hbm2java
 */
public class OrdenDeCompra  implements java.io.Serializable {


     private long ocId;
     private Proveedor proveedor;
     private Date ocFecha;
     private String ocGlosa;
     private String ocInfadicional;
     private String ocMonedacod;
     private String ocPorigencod;
     private String ocEstado;
     private Double totalgralOc;
     private Set cabecera101s = new HashSet(0);
     private Set items = new HashSet(0);

    public OrdenDeCompra() {
    }

	
    public OrdenDeCompra(long ocId) {
        this.ocId = ocId;
    }
    public OrdenDeCompra(long ocId, Proveedor proveedor, Date ocFecha, String ocGlosa, String ocInfadicional, String ocMonedacod, String ocPorigencod, String ocEstado, Double totalgralOc, Set cabecera101s, Set items) {
       this.ocId = ocId;
       this.proveedor = proveedor;
       this.ocFecha = ocFecha;
       this.ocGlosa = ocGlosa;
       this.ocInfadicional = ocInfadicional;
       this.ocMonedacod = ocMonedacod;
       this.ocPorigencod = ocPorigencod;
       this.ocEstado = ocEstado;
       this.totalgralOc = totalgralOc;
       this.cabecera101s = cabecera101s;
       this.items = items;
    }
   
    public long getOcId() {
        return this.ocId;
    }
    
    public void setOcId(long ocId) {
        this.ocId = ocId;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Date getOcFecha() {
        return this.ocFecha;
    }
    
    public void setOcFecha(Date ocFecha) {
        this.ocFecha = ocFecha;
    }
    public String getOcGlosa() {
        return this.ocGlosa;
    }
    
    public void setOcGlosa(String ocGlosa) {
        this.ocGlosa = ocGlosa;
    }
    public String getOcInfadicional() {
        return this.ocInfadicional;
    }
    
    public void setOcInfadicional(String ocInfadicional) {
        this.ocInfadicional = ocInfadicional;
    }
    public String getOcMonedacod() {
        return this.ocMonedacod;
    }
    
    public void setOcMonedacod(String ocMonedacod) {
        this.ocMonedacod = ocMonedacod;
    }
    public String getOcPorigencod() {
        return this.ocPorigencod;
    }
    
    public void setOcPorigencod(String ocPorigencod) {
        this.ocPorigencod = ocPorigencod;
    }
    public String getOcEstado() {
        return this.ocEstado;
    }
    
    public void setOcEstado(String ocEstado) {
        this.ocEstado = ocEstado;
    }
    public Double getTotalgralOc() {
        return this.totalgralOc;
    }
    
    public void setTotalgralOc(Double totalgralOc) {
        this.totalgralOc = totalgralOc;
    }
    public Set getCabecera101s() {
        return this.cabecera101s;
    }
    
    public void setCabecera101s(Set cabecera101s) {
        this.cabecera101s = cabecera101s;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


