package mapeo;
// Generated 26-03-2012 12:57:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private String perRut;
     private String perNombre;
     private String perApellido;
     private String perDireccion;
     private String perFono;
     private String perEmail;
     private Date perFnacimiento;
     private Set clientes = new HashSet(0);
     private Set trabajadors = new HashSet(0);

    public Persona() {
    }

	
    public Persona(String perRut) {
        this.perRut = perRut;
    }
    public Persona(String perRut, String perNombre, String perApellido, String perDireccion, String perFono, String perEmail, Date perFnacimiento, Set clientes, Set trabajadors) {
       this.perRut = perRut;
       this.perNombre = perNombre;
       this.perApellido = perApellido;
       this.perDireccion = perDireccion;
       this.perFono = perFono;
       this.perEmail = perEmail;
       this.perFnacimiento = perFnacimiento;
       this.clientes = clientes;
       this.trabajadors = trabajadors;
    }
   
    public String getPerRut() {
        return this.perRut;
    }
    
    public void setPerRut(String perRut) {
        this.perRut = perRut;
    }
    public String getPerNombre() {
        return this.perNombre;
    }
    
    public void setPerNombre(String perNombre) {
        this.perNombre = perNombre;
    }
    public String getPerApellido() {
        return this.perApellido;
    }
    
    public void setPerApellido(String perApellido) {
        this.perApellido = perApellido;
    }
    public String getPerDireccion() {
        return this.perDireccion;
    }
    
    public void setPerDireccion(String perDireccion) {
        this.perDireccion = perDireccion;
    }
    public String getPerFono() {
        return this.perFono;
    }
    
    public void setPerFono(String perFono) {
        this.perFono = perFono;
    }
    public String getPerEmail() {
        return this.perEmail;
    }
    
    public void setPerEmail(String perEmail) {
        this.perEmail = perEmail;
    }
    public Date getPerFnacimiento() {
        return this.perFnacimiento;
    }
    
    public void setPerFnacimiento(Date perFnacimiento) {
        this.perFnacimiento = perFnacimiento;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set trabajadors) {
        this.trabajadors = trabajadors;
    }




}


