package mapeo;
// Generated 26-03-2012 12:57:47 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private String prodCodigo;
     private Familia familia;
     private Tarjeta tarjeta;
     private String proNombre;
     private String proDescripcion;
     private Long proCantidad;
     private Double proCifuni;
     private Set items = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String prodCodigo, Familia familia) {
        this.prodCodigo = prodCodigo;
        this.familia = familia;
    }
    public Producto(String prodCodigo, Familia familia, Tarjeta tarjeta, String proNombre, String proDescripcion, Long proCantidad, Double proCifuni, Set items) {
       this.prodCodigo = prodCodigo;
       this.familia = familia;
       this.tarjeta = tarjeta;
       this.proNombre = proNombre;
       this.proDescripcion = proDescripcion;
       this.proCantidad = proCantidad;
       this.proCifuni = proCifuni;
       this.items = items;
    }
   
    public String getProdCodigo() {
        return this.prodCodigo;
    }
    
    public void setProdCodigo(String prodCodigo) {
        this.prodCodigo = prodCodigo;
    }
    public Familia getFamilia() {
        return this.familia;
    }
    
    public void setFamilia(Familia familia) {
        this.familia = familia;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }
    public String getProNombre() {
        return this.proNombre;
    }
    
    public void setProNombre(String proNombre) {
        this.proNombre = proNombre;
    }
    public String getProDescripcion() {
        return this.proDescripcion;
    }
    
    public void setProDescripcion(String proDescripcion) {
        this.proDescripcion = proDescripcion;
    }
    public Long getProCantidad() {
        return this.proCantidad;
    }
    
    public void setProCantidad(Long proCantidad) {
        this.proCantidad = proCantidad;
    }
    public Double getProCifuni() {
        return this.proCifuni;
    }
    
    public void setProCifuni(Double proCifuni) {
        this.proCifuni = proCifuni;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


