package mapeo;
// Generated 26-03-2012 12:57:47 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private String provRut;
     private String provNombre;
     private String provDireccion;
     private String provCiudad;
     private String provEmail;
     private String provEstado;
     private Set ordenDeCompras = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(String provRut) {
        this.provRut = provRut;
    }
    public Proveedor(String provRut, String provNombre, String provDireccion, String provCiudad, String provEmail, String provEstado, Set ordenDeCompras) {
       this.provRut = provRut;
       this.provNombre = provNombre;
       this.provDireccion = provDireccion;
       this.provCiudad = provCiudad;
       this.provEmail = provEmail;
       this.provEstado = provEstado;
       this.ordenDeCompras = ordenDeCompras;
    }
   
    public String getProvRut() {
        return this.provRut;
    }
    
    public void setProvRut(String provRut) {
        this.provRut = provRut;
    }
    public String getProvNombre() {
        return this.provNombre;
    }
    
    public void setProvNombre(String provNombre) {
        this.provNombre = provNombre;
    }
    public String getProvDireccion() {
        return this.provDireccion;
    }
    
    public void setProvDireccion(String provDireccion) {
        this.provDireccion = provDireccion;
    }
    public String getProvCiudad() {
        return this.provCiudad;
    }
    
    public void setProvCiudad(String provCiudad) {
        this.provCiudad = provCiudad;
    }
    public String getProvEmail() {
        return this.provEmail;
    }
    
    public void setProvEmail(String provEmail) {
        this.provEmail = provEmail;
    }
    public String getProvEstado() {
        return this.provEstado;
    }
    
    public void setProvEstado(String provEstado) {
        this.provEstado = provEstado;
    }
    public Set getOrdenDeCompras() {
        return this.ordenDeCompras;
    }
    
    public void setOrdenDeCompras(Set ordenDeCompras) {
        this.ordenDeCompras = ordenDeCompras;
    }




}


