package mapeo;
// Generated 26-03-2012 12:57:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta  implements java.io.Serializable {


     private String tarCodigo;
     private Date tarFecha;
     private Date tarFechacrea;
     private String tarEstado;
     private Set productos = new HashSet(0);

    public Tarjeta() {
    }

	
    public Tarjeta(String tarCodigo) {
        this.tarCodigo = tarCodigo;
    }
    public Tarjeta(String tarCodigo, Date tarFecha, Date tarFechacrea, String tarEstado, Set productos) {
       this.tarCodigo = tarCodigo;
       this.tarFecha = tarFecha;
       this.tarFechacrea = tarFechacrea;
       this.tarEstado = tarEstado;
       this.productos = productos;
    }
   
    public String getTarCodigo() {
        return this.tarCodigo;
    }
    
    public void setTarCodigo(String tarCodigo) {
        this.tarCodigo = tarCodigo;
    }
    public Date getTarFecha() {
        return this.tarFecha;
    }
    
    public void setTarFecha(Date tarFecha) {
        this.tarFecha = tarFecha;
    }
    public Date getTarFechacrea() {
        return this.tarFechacrea;
    }
    
    public void setTarFechacrea(Date tarFechacrea) {
        this.tarFechacrea = tarFechacrea;
    }
    public String getTarEstado() {
        return this.tarEstado;
    }
    
    public void setTarEstado(String tarEstado) {
        this.tarEstado = tarEstado;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


