package mapeo;
// Generated 26-03-2012 12:57:47 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Trabajador generated by hbm2java
 */
public class Trabajador  implements java.io.Serializable {


     private String perRut;
     private Persona persona;
     private Empresa empresa;
     private String areaTrabajo;
     private Date fechaContrato;
     private String pass;

    public Trabajador() {
    }

	
    public Trabajador(String perRut, Persona persona, Empresa empresa) {
        this.perRut = perRut;
        this.persona = persona;
        this.empresa = empresa;
    }
    public Trabajador(String perRut, Persona persona, Empresa empresa, String areaTrabajo, Date fechaContrato, String pass) {
       this.perRut = perRut;
       this.persona = persona;
       this.empresa = empresa;
       this.areaTrabajo = areaTrabajo;
       this.fechaContrato = fechaContrato;
       this.pass = pass;
    }
   
    public String getPerRut() {
        return this.perRut;
    }
    
    public void setPerRut(String perRut) {
        this.perRut = perRut;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getAreaTrabajo() {
        return this.areaTrabajo;
    }
    
    public void setAreaTrabajo(String areaTrabajo) {
        this.areaTrabajo = areaTrabajo;
    }
    public Date getFechaContrato() {
        return this.fechaContrato;
    }
    
    public void setFechaContrato(Date fechaContrato) {
        this.fechaContrato = fechaContrato;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


